name: 饿了么

on:
    workflow_dispatch:
    schedule:
        - cron: "10 12 * * *"
        - cron: "10 22 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: elem

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【饿了么】"
              run: |
                  node elem.js
              env:
                  cookie_elem: ${{ secrets.cookie_elem || github.event.client_payload.cookie_elem }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY || github.event.client_payload.PUSH_KEY }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN || github.event.client_payload.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID || github.event.client_payload.TG_USER_ID }}
