name: 京东签到

on:
    workflow_dispatch:
    schedule:
        # 每天00点01分定时运行
        - cron: "1 16 * * *"
        # 每天11点01分定时运行
        - cron: "1 3 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【京东签到】"
              run: |
                  node jdsign.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
