name: 什么值得买

on:
    workflow_dispatch:
    schedule:
        - cron: "0 18 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: smzdm

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【什么值得买】"
              run: |
                  node smzdm.js
              env:
                  SMZDM_ACCOUNTS: ${{ secrets.SMZDM_ACCOUNTS || github.event.client_payload.SMZDM_ACCOUNTS }}
                  SMZDM_COOKIES: ${{ secrets.SMZDM_COOKIES || github.event.client_payload.SMZDM_COOKIES }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY || github.event.client_payload.PUSH_KEY }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN || github.event.client_payload.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID || github.event.client_payload.TG_USER_ID }}
