name: 喜马拉雅

on:
    workflow_dispatch:
    schedule:
        # 定时任务，在每天的1点和20执行任务
        - cron: "0 17,12 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: ximalaya

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【喜马拉雅】"
              run: |
                  node ximalaya.js
              env:
                  XMLY_COOKIES: ${{ secrets.XMLY_COOKIES }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
